### ISSUE TITLE
Downloading dependency artifacts fails

### ISSUE THREAD

**Issue by markkumettala** [KierranM/teamcity-artifactory-artifact-storage-plugin#1]
We are using Artifact Dependencies and when testing with this plugin we get below error.
Has this feature tested or do we have something wrong in setup?
Uploading dependencies to artifactory works fine. Pressing the link and downloading artifact in the browser works also fine.

[10:26:07]
[Resolving artifact dependencies] Downloading 1 artifact
[10:26:08]
[Resolving artifact dependencies] Failed to resolve artifact dependency <TEST / TEST, build #14 [id 34]>: Failed to download file 'my_artifact.txt': Failed to download [http://xx.xx.xx.xx:8111/httpAuth/repository/download/Test_Test/34.tcbuildid/my_artifact.txt]: java.io.IOException: Illegal status [401] while downloading https://xxxxxxxx/Test/Test_Test/34/my_artifact.txt: Unauthorized (jetbrains.buildServer.artifacts.impl.SourcePathAwareResolvingFailedException)

**Comment by KierranM** [comment]
Sorry for missing this @markkumettala, for some reason GH didn't set me to watch my own repo 🤦‍♂ .

I can confirm I have this working on a production teamcity server. That error looks like it is due to the server not using credentials when downloading the file 🤔
