### ISSUE TITLE
Merge PRs

### ISSUE THREAD

**Issue by picchipalarm** [KierranM/teamcity-artifactory-artifact-storage-plugin#14]
Hi

Are you still active? any chance you can merge PR:
#12 Set Content-Type Header on response when it can be inferred.
#13 optionally parallelize uploading artifacts to Artifactory

**Comment by picchipalarm** [comment]
fork with both changes here:
https://github.com/picchipalarm/teamcity-artifactory-artifact-storage-plugin

**Comment by picchipalarm** [comment]
@kortov any chance you can merge?

**Comment by KierranM** [comment]
Sorry for taking a while to get onto this. I've merged your PRs and released the new versions to Jetbrains Plugin repo. Cheers!
